[package]
name = "altr"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CLI tool to alter words seamlessly while preserving casing"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
